# Generated by Django 2.2.6 on 2021-04-28 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('illust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間'),
        ),
    ]
